version: "2"
services:
    rabbit:
        image:
            rabbitmq:3-management
        ports:
            - "15672:15672"
        environment:
          - RABBITMQ_DEFAULT_USER=stackrabbit
          - RABBITMQ_DEFAULT_PASS=password
        networks:
            cnalan:
                aliases:
                    - rabbit
    redis:
        image:
            redis
        networks:
            cnalan:
                aliases:
                    - redis
    db:
        build:
            context: db
        environment:
          - MYSQL_ROOT_PASSWORD=toto
          - MYSQL_DATABASE=prestashop
          - MYSQL_USER=prestashop
          - MYSQL_PASSWORD=prestashop1234
        networks:
            cnalan:
                aliases:
                    - db
    web:
        build:
            context: web
        ports:
            - "80:80"
        links:
          - i
          - s
          - b
          - p
        networks:
            cnalan:
    i:
        build:
            context: microservices/i
        links:
            - db
        networks:
            cnalan:
              aliases:
                - i
    s:
        build:
            context: microservices/s
        links:
            - redis
        networks:
            cnalan:
              aliases:
                - s
    b:
        build:
            context: microservices/b
        links:
            - w
            - rabbit
        networks:
            cnalan:
              aliases:
                - b
    p:
        build:
            context: microservices/p
        networks:
            cnalan:
              aliases:
                - p
    w:
        build:
            context: microservices/w
        networks:
            cnalan:
              aliases:
                - w
    w1:
        build:
            context: microservices/w1
        links:
          - rabbit
          - redis
        networks:
            cnalan:
              aliases:
                - w1
    w2:
        build:
            context: microservices/w2
        links:
          - rabbit
        environment:
          - W2_APIKEY=key-blabla
          - W2_TO=mail@bla
          - W2_DOMAIN=mydomain
        networks:
            cnalan:
              aliases:
                - w2
networks:
    cnalan:
        driver: bridge
